/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace EncryptedHighLow {
  export type GameSummaryStruct = {
    creator: AddressLike;
    minStake: BigNumberish;
    createdAt: BigNumberish;
    endTime: BigNumberish;
    rewardPool: BigNumberish;
    totalPot: BigNumberish;
    revealPending: boolean;
    settled: boolean;
    autoSettleEnabled: boolean;
    revealedNumber: BigNumberish;
    numberIsBig: boolean;
    winnersCount: BigNumberish;
    creatorShare: BigNumberish;
    payoutPerWinner: BigNumberish;
    participantCount: BigNumberish;
    creatorClaimed: boolean;
  };

  export type GameSummaryStructOutput = [
    creator: string,
    minStake: bigint,
    createdAt: bigint,
    endTime: bigint,
    rewardPool: bigint,
    totalPot: bigint,
    revealPending: boolean,
    settled: boolean,
    autoSettleEnabled: boolean,
    revealedNumber: bigint,
    numberIsBig: boolean,
    winnersCount: bigint,
    creatorShare: bigint,
    payoutPerWinner: bigint,
    participantCount: bigint,
    creatorClaimed: boolean
  ] & {
    creator: string;
    minStake: bigint;
    createdAt: bigint;
    endTime: bigint;
    rewardPool: bigint;
    totalPot: bigint;
    revealPending: boolean;
    settled: boolean;
    autoSettleEnabled: boolean;
    revealedNumber: bigint;
    numberIsBig: boolean;
    winnersCount: bigint;
    creatorShare: bigint;
    payoutPerWinner: bigint;
    participantCount: bigint;
    creatorClaimed: boolean;
  };

  export type ParticipantViewStruct = {
    stake: BigNumberish;
    exists: boolean;
    won: boolean;
    claimed: boolean;
    choiceRevealed: boolean;
    guessedBig: boolean;
  };

  export type ParticipantViewStructOutput = [
    stake: bigint,
    exists: boolean,
    won: boolean,
    claimed: boolean,
    choiceRevealed: boolean,
    guessedBig: boolean
  ] & {
    stake: bigint;
    exists: boolean;
    won: boolean;
    claimed: boolean;
    choiceRevealed: boolean;
    guessedBig: boolean;
  };
}

export interface EncryptedHighLowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_CREATOR_REWARD"
      | "MIN_DURATION"
      | "MIN_STAKE"
      | "autoSettle"
      | "claimCreator"
      | "claimWinnings"
      | "createGame"
      | "debugReveal"
      | "fairReveal"
      | "getEncryptedSecret"
      | "getGame"
      | "getParticipant"
      | "joinGame"
      | "listParticipants"
      | "nextGameId"
      | "protocolId"
      | "requestReveal"
      | "revealCallback"
      | "totalGames"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CreatorClaimed"
      | "DecryptionFulfilled"
      | "GameCreated"
      | "GameJoined"
      | "GameSettled"
      | "RevealRequested"
      | "WinningsClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MIN_CREATOR_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MIN_STAKE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "autoSettle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimCreator",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimWinnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createGame",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "debugReveal",
    values: [BigNumberish, BigNumberish, boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "fairReveal",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedSecret",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGame",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipant",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinGame",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listParticipants",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextGameId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestReveal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revealCallback",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalGames",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_CREATOR_REWARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_STAKE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "autoSettle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "debugReveal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fairReveal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedSecret",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getParticipant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joinGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "listParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextGameId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestReveal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalGames", data: BytesLike): Result;
}

export namespace CreatorClaimedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    creator: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [gameId: bigint, creator: string, amount: bigint];
  export interface OutputObject {
    gameId: bigint;
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptionFulfilledEvent {
  export type InputTuple = [requestID: BigNumberish];
  export type OutputTuple = [requestID: bigint];
  export interface OutputObject {
    requestID: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameCreatedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    creator: AddressLike,
    minStake: BigNumberish,
    endTime: BigNumberish,
    rewardPool: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    creator: string,
    minStake: bigint,
    endTime: bigint,
    rewardPool: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    creator: string;
    minStake: bigint;
    endTime: bigint;
    rewardPool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameJoinedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    stake: BigNumberish
  ];
  export type OutputTuple = [gameId: bigint, player: string, stake: bigint];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameSettledEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    revealedNumber: BigNumberish,
    numberIsBig: boolean,
    winnersCount: BigNumberish,
    creatorShare: BigNumberish,
    payoutPerWinner: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    revealedNumber: bigint,
    numberIsBig: boolean,
    winnersCount: bigint,
    creatorShare: bigint,
    payoutPerWinner: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    revealedNumber: bigint;
    numberIsBig: boolean;
    winnersCount: bigint;
    creatorShare: bigint;
    payoutPerWinner: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevealRequestedEvent {
  export type InputTuple = [gameId: BigNumberish, requestId: BigNumberish];
  export type OutputTuple = [gameId: bigint, requestId: bigint];
  export interface OutputObject {
    gameId: bigint;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinningsClaimedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [gameId: bigint, player: string, amount: bigint];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedHighLow extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedHighLow;
  waitForDeployment(): Promise<this>;

  interface: EncryptedHighLowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_CREATOR_REWARD: TypedContractMethod<[], [bigint], "view">;

  MIN_DURATION: TypedContractMethod<[], [bigint], "view">;

  MIN_STAKE: TypedContractMethod<[], [bigint], "view">;

  autoSettle: TypedContractMethod<
    [gameId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  claimCreator: TypedContractMethod<
    [gameId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimWinnings: TypedContractMethod<
    [gameId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createGame: TypedContractMethod<
    [
      secretNumberHandle: BytesLike,
      inputProof: BytesLike,
      secretNumberHash: BytesLike,
      minStake: BigNumberish,
      endTime: BigNumberish,
      rewardPool: BigNumberish,
      enableAutoSettle: boolean
    ],
    [bigint],
    "payable"
  >;

  debugReveal: TypedContractMethod<
    [gameId: BigNumberish, revealedNumber: BigNumberish, guesses: boolean[]],
    [boolean],
    "nonpayable"
  >;

  fairReveal: TypedContractMethod<
    [gameId: BigNumberish, originalSecretNumber: BigNumberish, salt: BytesLike],
    [boolean],
    "nonpayable"
  >;

  getEncryptedSecret: TypedContractMethod<
    [gameId: BigNumberish],
    [string],
    "view"
  >;

  getGame: TypedContractMethod<
    [gameId: BigNumberish],
    [EncryptedHighLow.GameSummaryStructOutput],
    "view"
  >;

  getParticipant: TypedContractMethod<
    [gameId: BigNumberish, account: AddressLike],
    [EncryptedHighLow.ParticipantViewStructOutput],
    "view"
  >;

  joinGame: TypedContractMethod<
    [gameId: BigNumberish, guessHandle: BytesLike, inputProof: BytesLike],
    [void],
    "payable"
  >;

  listParticipants: TypedContractMethod<
    [gameId: BigNumberish],
    [string[]],
    "view"
  >;

  nextGameId: TypedContractMethod<[], [bigint], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  requestReveal: TypedContractMethod<
    [gameId: BigNumberish],
    [void],
    "nonpayable"
  >;

  revealCallback: TypedContractMethod<
    [
      requestId: BigNumberish,
      cleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  totalGames: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_CREATOR_REWARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "autoSettle"
  ): TypedContractMethod<[gameId: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "claimCreator"
  ): TypedContractMethod<[gameId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimWinnings"
  ): TypedContractMethod<[gameId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createGame"
  ): TypedContractMethod<
    [
      secretNumberHandle: BytesLike,
      inputProof: BytesLike,
      secretNumberHash: BytesLike,
      minStake: BigNumberish,
      endTime: BigNumberish,
      rewardPool: BigNumberish,
      enableAutoSettle: boolean
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "debugReveal"
  ): TypedContractMethod<
    [gameId: BigNumberish, revealedNumber: BigNumberish, guesses: boolean[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fairReveal"
  ): TypedContractMethod<
    [gameId: BigNumberish, originalSecretNumber: BigNumberish, salt: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedSecret"
  ): TypedContractMethod<[gameId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getGame"
  ): TypedContractMethod<
    [gameId: BigNumberish],
    [EncryptedHighLow.GameSummaryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getParticipant"
  ): TypedContractMethod<
    [gameId: BigNumberish, account: AddressLike],
    [EncryptedHighLow.ParticipantViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinGame"
  ): TypedContractMethod<
    [gameId: BigNumberish, guessHandle: BytesLike, inputProof: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "listParticipants"
  ): TypedContractMethod<[gameId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "nextGameId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestReveal"
  ): TypedContractMethod<[gameId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revealCallback"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      cleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalGames"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "CreatorClaimed"
  ): TypedContractEvent<
    CreatorClaimedEvent.InputTuple,
    CreatorClaimedEvent.OutputTuple,
    CreatorClaimedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptionFulfilled"
  ): TypedContractEvent<
    DecryptionFulfilledEvent.InputTuple,
    DecryptionFulfilledEvent.OutputTuple,
    DecryptionFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "GameCreated"
  ): TypedContractEvent<
    GameCreatedEvent.InputTuple,
    GameCreatedEvent.OutputTuple,
    GameCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GameJoined"
  ): TypedContractEvent<
    GameJoinedEvent.InputTuple,
    GameJoinedEvent.OutputTuple,
    GameJoinedEvent.OutputObject
  >;
  getEvent(
    key: "GameSettled"
  ): TypedContractEvent<
    GameSettledEvent.InputTuple,
    GameSettledEvent.OutputTuple,
    GameSettledEvent.OutputObject
  >;
  getEvent(
    key: "RevealRequested"
  ): TypedContractEvent<
    RevealRequestedEvent.InputTuple,
    RevealRequestedEvent.OutputTuple,
    RevealRequestedEvent.OutputObject
  >;
  getEvent(
    key: "WinningsClaimed"
  ): TypedContractEvent<
    WinningsClaimedEvent.InputTuple,
    WinningsClaimedEvent.OutputTuple,
    WinningsClaimedEvent.OutputObject
  >;

  filters: {
    "CreatorClaimed(uint256,address,uint256)": TypedContractEvent<
      CreatorClaimedEvent.InputTuple,
      CreatorClaimedEvent.OutputTuple,
      CreatorClaimedEvent.OutputObject
    >;
    CreatorClaimed: TypedContractEvent<
      CreatorClaimedEvent.InputTuple,
      CreatorClaimedEvent.OutputTuple,
      CreatorClaimedEvent.OutputObject
    >;

    "DecryptionFulfilled(uint256)": TypedContractEvent<
      DecryptionFulfilledEvent.InputTuple,
      DecryptionFulfilledEvent.OutputTuple,
      DecryptionFulfilledEvent.OutputObject
    >;
    DecryptionFulfilled: TypedContractEvent<
      DecryptionFulfilledEvent.InputTuple,
      DecryptionFulfilledEvent.OutputTuple,
      DecryptionFulfilledEvent.OutputObject
    >;

    "GameCreated(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;
    GameCreated: TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;

    "GameJoined(uint256,address,uint256)": TypedContractEvent<
      GameJoinedEvent.InputTuple,
      GameJoinedEvent.OutputTuple,
      GameJoinedEvent.OutputObject
    >;
    GameJoined: TypedContractEvent<
      GameJoinedEvent.InputTuple,
      GameJoinedEvent.OutputTuple,
      GameJoinedEvent.OutputObject
    >;

    "GameSettled(uint256,uint8,bool,uint256,uint256,uint256)": TypedContractEvent<
      GameSettledEvent.InputTuple,
      GameSettledEvent.OutputTuple,
      GameSettledEvent.OutputObject
    >;
    GameSettled: TypedContractEvent<
      GameSettledEvent.InputTuple,
      GameSettledEvent.OutputTuple,
      GameSettledEvent.OutputObject
    >;

    "RevealRequested(uint256,uint256)": TypedContractEvent<
      RevealRequestedEvent.InputTuple,
      RevealRequestedEvent.OutputTuple,
      RevealRequestedEvent.OutputObject
    >;
    RevealRequested: TypedContractEvent<
      RevealRequestedEvent.InputTuple,
      RevealRequestedEvent.OutputTuple,
      RevealRequestedEvent.OutputObject
    >;

    "WinningsClaimed(uint256,address,uint256)": TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
    WinningsClaimed: TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
  };
}
